### ISSUE TITLE
kafka.errors.NoBrokersAvailable when launch containers.

### ISSUE THREAD

**Issue by ivanmsiegfried** [PedroDSFerreira/osm-mec#52]
I'm trying to deploy osm-mec on ubuntu 20.04. All of the requirements were installed. 

when I run this

`docker compose up --build`

Got this error

```bash
oss-1                 |     client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
oss-1                 |   File "/usr/local/lib/python3.8/site-packages/kafka/client_async.py", line 244, in __init__
oss-1                 |     self.config['api_version'] = self.check_version(timeout=check_timeout)
oss-1                 |   File "/usr/local/lib/python3.8/site-packages/kafka/client_async.py", line 900, in check_version
oss-1                 |     raise Errors.NoBrokersAvailable()
oss-1                 | kafka.errors.NoBrokersAvailable: NoBrokersAvailable

```

Any suggestions what to look for? Thanks

**Comment by PedroDSFerreira** [comment]
Make sure that you have a Kafka instance up and running. You have two options to accomplish this:
- [Expose the port of OSM's internal Kafka](https://osm.etsi.org/wikipub/index.php/Developer_HowTo#7_Expose_needed_ports_of_docker_services)
- Set up a new container for running Kafka outside of OSM.

If you choose the second option, add to `docker-compose.yaml` the following services:
```yaml
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: yes
    restart: on-failure

  kafka:
    image: "wurstmeister/kafka:latest"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    restart: on-failure
```

And update the env variable `KAFKA_BOOTSTRAP_SERVERS=kafka:9092` in OSS and MEAO services.
